
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
trigger:
  branches:
    include:
      - master  # Usando la rama master

pool:
  name: 'Default'  # Usando agente Windows

steps:
- task: Gradle@2  # Usando la tarea Gradle estándar
  inputs:
    gradleWrapperFile: './gradlew'  # Ruta al Gradle Wrapper (si estás usando uno)
    options: 'gradlew clean test aggregate'  # Comando de Gradle para limpiar y ejecutar pruebas
    gradleHome: '$(Build.SourcesDirectory)/gradle'  # Si necesitas un directorio de Gradle específico, puedes configurarlo

