trigger:
  branches:
    include:
      - master  # Usando la rama master

pool:
  name: 'Default'  # Usando agente Windows
  
stages:
- stage: Build_and_Test
  displayName: Build and Test Automation Project
  jobs:
  - job: Run_Tests
    displayName: Build and Run Tests
    steps:
    # 1. Descargar el código desde el repositorio
    - task: Checkout@1
      displayName: "Clonar el código del repositorio"

    # 2. Compilar el proyecto y ejecutar pruebas
    - script: |
        echo Compilando el proyecto y ejecutando pruebas...
        ./gradlew clean test aggregate
      displayName: "Compilar y ejecutar pruebas con Gradle"

    # 3. Publicar resultados de pruebas (JUnit)
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/build/test-results/test/*.xml'  # Ruta de los archivos de resultados de prueba generados por Gradle
        testRunTitle: 'Resultados de pruebas automatizadas'
